version: '3.8'

services:
  devenv:
    container_name: devenv
    build: 
      context: .
      dockerfile: Dockerfile

    network_mode: service:pgdb
    
    volumes:
      - ../..:/workspaces:cached

    depends_on:
      - pgdb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    network_mode: service:pgdb

    volumes:
      - vpgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@abcd.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    restart: unless-stopped
    container_name: pgdb
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: localdbpassword
      POSTGRES_USER: puser
      POSTGRES_DB: testdb1

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
  vpgadmin:
